name: StatsMe
main: BoxOfDevs\StatsMe\main
version: 1.0.0
api: [1.14.0, 2.0.0]
    
commands:
    stats:
        description: "Shows your stats."
        usage: "/stats"
        
permissions:
    statsme.my:
        default: true
        description: "Allows you to get your stats."
    statsme.other:
        default: true
        description: "Allows you to get the stats of other players."
