---
#    ____  _        _       __  __
#   / ___|| |_ __ _| |_ ___|  \/  | ___
#   \___ \| __/ _` | __/ __| |\/| |/ _ \
#    ___) | || (_| | |_\__ \ |  | |  __/
#   |____/ \__\__,_|\__|___/_|  |_|\___|
# Config for StatsMe
# 
# Available variables:
# {firstline} - Set the first line (or any other line) depending on if the player gets the own stats or the stats of other players.
# If the payer gets the own stats, the text will be:
firstline_mystats: "&e&lYour stats:"
# If the player gets another players stats, the text will be:
firstline_otherstats: "&e&l{name}s stats:"
# {name} - The player's name
# {healt} -  The player's health
# {maxhealth} - The player's maximum health
# {hearts} - The player's health displayed with heart symbols (choose one underneath)
heartsymbol: "โค"
# {coins} - The player's coins (needs economyAPI by onebone)
# {xyz} - The position of the player
# 
# Formatting variables:
# & - Use this instead of ยง (paragraph) to color the text a list of color codes can be found here: http://minecraft.gamepedia.com/Formatting_codes#Color_codes
# {line} - Use this instead of \n to make a new line
# 
# The text shown when a player does /stats:
stats: "{firstline}{line}&aName:&f {name}{line}&cHealth: &f{health}/{maxhealth}{line}&cHearts: {hearts}{line}&6Coins:&f {coins}{line}&bXYZ:&f {xyz}"
...
